# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.cache/wt [current_project]
set_property parent.project_path D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property board_part e-elements.com:ego1:part0:1.0 [current_project]
set_property ip_output_repo d:/Code/riscv-fpga-cpu/cpu_project/cpu_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/ALU.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/CPUTop.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/CPUTopPipeline.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/DataMemory.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/DebugController.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/Decoder.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/HazardUnit.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/Ifetch.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/Ifetch_Pipe.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/ImmGen.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/PipeRegs.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/RegFile.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/RegFile_Pipe.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/UartRx.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/UartTx.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/VGA.v
  D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/sources_1/new/TopDebug.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/constrs_1/ego1.xdc
set_property used_in_implementation false [get_files D:/Code/riscv-fpga-cpu/cpu_project/cpu_project.srcs/constrs_1/ego1.xdc]


synth_design -top TopDebug -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopDebug.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopDebug_utilization_synth.rpt -pb TopDebug_utilization_synth.pb"
